# Generated by Django 6.0.5 on 2026-05-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuIten',
            new_name='MenuItem',
        ),
    ]
