# Generated by Django 6.0.5 on 2026-05-25 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
